- examples/ex_pose_goal.py
- pymoveit2/moveit2.py
Hi,
thank you for writing this, especially with the good examples :)
I missed the cartesian planner, so i added it here. 
I don't know why the moveit2 interface is so weird, but the code works (and calls the same service as the GUI in rviz does i think).
closes #6
> Add support for Cartesian paths

- pymoveit2/moveit2.py
Although `target_link` is a parameter to `move_to_pose`, it isn't used if `self.__execute_via_moveit` is False. This PR addresses that, by adding a `target_link` parameter to `plan`.
> Add `target_link` param to `plan`

- pymoveit2/gripper_command.py
- pymoveit2/gripper_interface.py
- pymoveit2/moveit2.py
This PR simplifies the usage of this interface.
- Make API for Cartesian paths more obvious
- Allow passing `Pose` and `PoseStamped` as pose goal
- Make `wait_until_executed()` return success of execution
> Simplify usage

- pymoveit2/robots/lbr.py
Hi @AndrejOrsula and thank you for this great work!
We recently found that users requested help with moveit and I think your repository simplifies interfacing it greatly.
This pull request aims to add support for KUKA LBRs (iiwa7, iiwa14, med7, med14) in https://github.com/lbr-stack/lbr_fri_ros2_stack.
In the `lbr_fri_ros2_stack` everything is namespaced by robot name, that includes for example `/move_action` action server.
Could you please help us integrate?
Or would you rather recommend to use the moveit python bindings?
Thank you for the help!
> Add support for KUKA LBRs

- examples/ex_gripper.py
- examples/ex_joint_goal.py
- examples/ex_pose_goal.py
- pymoveit2/__init__.py
- pymoveit2/gripper_interface.py
- pymoveit2/moveit2.py
- pymoveit2/moveit2_gripper.py
The primary goal of this PR is to enable users of `pymoveit2` to plan and/or execute asynchronously. This is useful to allow users to cancel planning/execution calls, and to allow the main thread to continue executing during planning/execution (e.g., we use `pymoveit2` within a [behavior tree framework](https://py-trees.readthedocs.io/en/devel/), so the tree must be able to continue ticking as the robot is moving). 
Changes 1-2 below tackle that primary goal. As part of tackling the primary goal, some additional changes also made sense; those are Changes 3-4, which are justified below.
1. Make action execution (both `MoveGroup` and controller execution) asynchronous. Track the state of the action with a new enum, `MoveIt2State`, and allow users to query the state and cancel execution.
2. …
> Add asynchronous planning and execution

- CMakeLists.txt
- examples/ex_orientation_path_constraint.py
- pymoveit2/moveit2.py
MoveIt2 allows planning with path constraints (e.g., see [here](https://moveit.picknik.ai/main/doc/how_to_guides/using_ompl_constrained_planning/ompl_constrained_planning.html)) but `pymoveit2` does not currently support it. This PR does the following:
1. Separates the logic to create constraints from the logic to set goal constraints, so that the constraint creation functions can be reused.
2. Extends the API to allow for setting orientation, position, and joint constraints as path constraints (in addition to the existing option of setting them as goal constraints).
3. Adds an example showcasing the orientation path constraint capability.
Note that this PR is joint with [`panda_ign_moveit2`#29](https://github.com/AndrejOrsula/panda_ign_moveit2/pull/29), which enables [OMPL Constrained …
> Add Path Constraints

- CMakeLists.txt
- examples/ex_fk.py
- examples/ex_ik.py
- examples/ex_orientation_path_constraint.py
- pymoveit2/moveit2.py
Similar to #40 , this PR adds the ability to asynchronously call forward or inverse kinematics, along with corresponding examples.
> Added Async Forward/Inverse Kinematics

- examples/ex_joint_goal.py
- examples/ex_pose_goal.py
- pymoveit2/moveit2.py
Currently, `pymoveit2` implicitly uses the default `pipeline_id` and `planner_id` that the robot was configured with. However, for different motions, one may want to use different pipelines/planners. Hence, this PR allows users to configure those properties of the planning calls.
> Allow users to set `planner_id` and `pipeline_id`

- pymoveit2/moveit2.py
There has been an update in the msg format of moveit_msgs mentioned in the CHANGELOG 0.11.3 (2022-09-13) [link](https://github.com/ros-planning/moveit_msgs/blob/9756797dcbc293c7cae66541a7bc0c7acec85892/CHANGELOG.rst#L12)
It seems like the update in moveit_msgs was not included in the moveit releases until the iron release.
This was causing an error with iron and the current rolling version of moveit:
```
no member name found cartesian_speed_end_effector_link
```
I have tested the PR my local and it now works fine in both iron and rolling after updating the msg format. 
Given that it seems that the main branch of pymoveit2 is targeting humble, maybe this should be a part of your new release [3.2.0](https://github.com/AndrejOrsula/pymoveit2/pull/41)?
> Update msg format to support ROS Iron

- CMakeLists.txt
- examples/ex_allow_collisions.py
- pymoveit2/moveit2.py
This PR extendes `pymoveit2` to allow users to (dis)allow collisions between one object and all other objects. In practice, this is useful because a robot typically consists of many objects/links, so instead of specifying every object ID for a robot part that we want to (dis)allow collisions with, it is easier to just (dis)allow collisions with all objects, which includes the whole robot.
- Note that although (dis)allowing collisions is asynchronous, within the call it synchronously waits for the planning scene. This should be improved in the future to make it a fully asynchronous call (maybe `pymoveit2` subscribes to the MoveGroup's published planning scene topic so it constantly maintains an upt-to-date planning scene?).
- This PR (dis)allows collisions between one object and all other …
> Allow users to (dis)allow collisions with an object

- pymoveit2/moveit2.py
- Continues https://github.com/AndrejOrsula/pymoveit2/pull/49 based on the discussion there
- Fixes https://github.com/AndrejOrsula/pymoveit2/issues/55
> Use `cartesian_speed_limited_link` instead of `cartesian_speed_end_effector_link` when available

- pymoveit2/moveit2.py
This PR fixes the issue #45 by changing the max_cartesian_speed setter to set the max_velocity_scaling_factor of the cartesian_path_request.
This PR also adds a max_cartesian_acceleration setter and getter to set the max_acceleration_scaling_factor of the cartesian_path_request.
Tested with a real and simulated franka panda robot via the move_to_pose command with the cartesian flag set to true.
I used the BiTRRT algorithm from the OMPL and the PTP algorithm from the PILZ trajectory generator.
> Added setting of cartesian speed and acceleration 

- examples/ex_collision_mesh.py
- examples/ex_collision_primitive.py
- pymoveit2/moveit2.py
This PR implements the ability to move collision objects, and extends corresponding examples.
> Add ability to move collision objects

- pymoveit2/moveit2.py
This PR makes two small changes:
1. **Bug fix**: the `GetCartesianPath` parameters added in #53 exist in [Iron](https://github.com/moveit/moveit_msgs/blob/iron/srv/GetCartesianPath.srv) but not in [Humble](https://github.com/moveit/moveit_msgs/blob/humble/srv/GetCartesianPath.srv). This PR fixes that by checking if those attributes exist before assigning them.
2. **New capability**: Although `MoveIt2` had the ability to get and access the latest planning scene, that was not exposed to users. this PR addresses that.
(I'm happy to separate this into two PRs if you prefer -- I made it a joint PR for now given how small each change is.)
> Reinstate Humble Compatibility for `GetCartesianPath` & Expose `planning_scene` To User

- pymoveit2/moveit2.py
My previous PR, #66 , was not thoroughly tested and introduced a bug. This PR resolves that bug, and thoroughly tests it this time. Sorry for overlooking the bug!
> Fix bug in cartesian planning

- examples/ex_collision_mesh.py
- pymoveit2/moveit2.py
In my application, I sometimes have to do computations on the mesh before adding it in the collision scene. To avoid loading a mesh twice, this PR allows users to either pass in the mesh filepath, or pass in the mesh itself.
> Allow users to preload a collision mesh

- .pre-commit-config.yaml
- CMakeLists.txt
- README.md
- examples/ex_allow_collisions.py
- examples/ex_collision_mesh.py
- examples/ex_collision_primitive.py
- examples/ex_pose_goal.py
- pymoveit2/moveit2.py
- #50 
- #56
- #53 
- Breaking change, `max_cartesian_speed` property is removed
- #58 
- #59 
- #62 
- #67
- #66
- #68
-
> Development towards 4.0.0

- CMakeLists.txt
- examples/ex_clear_planning_scene.py
- pymoveit2/moveit2.py
Although users can theoretically remove all collision obejcts by removing them one-at-a-time with `remove_collision_object`, that process has two downsides: (a) it is slow; and (b) collision object updates that are sent via topic publication are not always processed by MoveIt, particularly if multiple are sent in quick succession.
Thus, this PR adds the ability for users to clear all collision objects in the planning scene via service call.
I'm okay with either merging it to `master` or `devel`. Since it strictly adds functionality, perhaps it only needs to be a minor release?
> Allow clearing all collision objects

- pymoveit2/moveit2.py
In general, it is best practice to initial all parameters before ROS interfaces that have callbacks. Because as soon as we initialize the ROS2 interfaces, they can theoretically be called, even if their necessary parameters are not yet initialized.
A real-world example I faced on a particularly slow computer:
1. `__init__` created the joint state subscriber, but did not yet create `self.__joint_names`
2. The first joint state message was received.
3. The code crashed (because `self.__joint_names`) does not exist.
This PR should address issues like that.
> Initialize parameters before ROS2 callbacks

- pymoveit2/moveit2.py
#67 allowed users to pass in a preloaded mesh as a parameter, to avoid needing to keep reloading a mesh. That PR correctly realized that if the mesh is passed in as a parameter, we should copy it before scaling, to avoid destructively modifying the mesh that the user passed in. However, that PR had a bug in its implementation of that feature, resulting in it copying the mesh before scaling if the mesh was _not_ passed in as a parameter. This PR addresses that.
I tested this PR on my local robot setup, where we pre-load a mesh and then add it multiple times with different scale values. Before the change, the mesh would keep scaling down until near-zero (because the pre-loaded mesh is what gets scaled). After the change, it properly applies the scale (because the pre-loaded mesh remains …
> [Bugfix] Copy mesh before scaling if it was passed in as a parameter

- pymoveit2/moveit2.py
1. Replace `rate.sleep()` with `rclpy.spin_once(self._node, timeout_sec=1.0)` to avoid sleeping forever.
2. Ensure Start Joint States Are present.
3. Wait for the ROS2 Services to make sure they are available.
> Fix potential deadlock and wait until service is available

- pymoveit2/moveit2.py
Can't use rclpy.spin unless rclpy is imported.
Also, wait_until_executed use of spin was incorrect.
> Fix rclpy import and spin issues from (#87)

- pymoveit2/moveit2.py
This PR fixes a potential issue introduced in [1f030f6](https://github.com/AndrejOrsula/pymoveit2/commit/1f030f6072dac16914c91d1368926f182ea5f1fc), where rclpy.spin_once() was called without passing the node's executor.
Calling spin_once(node) without an explicit executor causes the node to be added to a global executor temporarily and then removed. If the node was already attached to a custom MultiThreadedExecutor, this breaks subsequent usage and can result in runtime exceptions in rclpy's event_handler.py, like:
`IndexError: wait set index too big`
The fix is to call:
`rclpy.spin_once(node, executor=node.executor, timeout_sec=...)`
so that the node stays associated with the correct executor.
This is inline with a recent change in `spin_once()' that was introduced …
> Always specify executor when spinning the node

- package.xml
- pymoveit2/moveit2.py
- pymoveit2/moveit2_gripper.py
Just cleaning up some unused variables and parameters. This breaks API.
This also reverts https://github.com/AndrejOrsula/pymoveit2/pull/94 due to https://github.com/AndrejOrsula/pymoveit2/issues/95.
> Revert #94, add trimesh to ROS dependencies, and remove sync param from `reset_controller()` methods

- package.xml
As discussed in https://github.com/AndrejOrsula/pymoveit2/pull/97#issuecomment-2870213121, the `python3-trimesh-pip` rosdep key is resolved to a pip package, which cannot be used for bloom releases. A [`python3-trimesh`](https://packages.ubuntu.com/plucky/python3-trimesh) Debian package is available for Ubuntu 25.04 onwards and could be used for the next ROS LTS release.
> comment out trimesh pip dependency for bloom package

- .github/workflows/build.yml
Add [ros-deb-builder-action](https://github.com/jspricke/ros-deb-builder-action) CI workflow, as suggested by @christian-rauch in https://github.com/AndrejOrsula/pymoveit2/issues/92#issuecomment-2851477275.
> CI: Add build workflow

- pymoveit2/moveit2.py
This feature would enable users to edit the workspace parameters for plan requests. Currently, I don't believe that there is an alternative since these are private attributes. Though please correct me if I am wrong :)
> Add a method for setting the workspace parameters

- pymoveit2/moveit2.py
**Problem:**
Currently, it is not possible to specify the link name on which the inverse kinematics calculation should be based. The default is always the last link of the planning group defined by the group_name parameter.
**Solution:**
This PR adds the ability to set the ik_link_name parameter when calling `compute_ik(...)` or `compute_ik_async(...)`. This allows calculating IK for poses relative to different frames by exposing the `self.__compute_ik_req.ik_request.ik_link_name` variable, which was not configurable before.
> expose ik_link_name argument to compute_ik()

- pymoveit2/moveit2.py
Currently, even when a `custom_start_state` is passed, the `MotionPlanRequest.start_state` is left unset, causing MoveIt to see an empty start state and fall back to the planning scene’s current state.
This patch ensures that `plan_async` explicitly assigns the provided `start_joint_state` (or defaults to the latest observed joint state), so requests now include the intended start state and avoid adaptor warnings.
Testing this resulted in our plans working as expected when providing a custom start state.
> Apply the custom start joint state to the request
